# Generated by Django 4.2.7 on 2025-12-03 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_category_options_alter_user_budget_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field cannot contain numbers or special characters.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('Canada', 'Canada'), ('US', 'US')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field cannot contain numbers or special characters.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field cannot contain numbers or special characters.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid US/Canadian phone number.', regex='^\\+?1?\\s?[-.()]?\\s?\\d{3}[-.()]?\\s?\\d{3}[-.()]?\\s?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='This field cannot contain numbers or special characters.', regex='^[A-Za-z\\s\\-]+$')]),
        ),
    ]
